language:
  - python

notification:
  email:
    on_success: never
    on_failure: always

python:
  - 3.4
  - 3.6

services:
  - postgresql

before_install:
  - pip3 install --upgrade pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd oshc/
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput

script:
  - flake8 .
  - coverage run --source='main' manage.py test --verbosity 2

after_success:
  - coverage report
  - coveralls
